# Use postgres/example user/password credentials
version: '3.9'
services:

  postgres:
    image: postgres
    restart: "no"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123@123A
      PGDATA: /var/lib/postgresql/data/pgdata 

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: azsimplebankapi
    ports:
      - 8888:8888
    environment:
      DB_SOURCE: postgresql://postgres:123%40123A@postgres:5432/simple_bank?sslmode=disable
      GIN_MODE: release
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]