# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: "no"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123@123A
      PGDATA: /var/lib/postgresql/data/pgdata 

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080